swagger: "2.0"
info:
  version: 1.0.0
  title: google-movies-scraper
  description: A simple API to scrape google.com/movies.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Steven Pollack
    email: steven@gnobel.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: google-movies-scraper.herokuapp.com
basePath: /
schemes:
  - http
produces:
  - application/json
paths:
  /movies:
    get:
      description: Return all theatres (and their showtimes) displayed in a call to google.com/movies.
      parameters:
        - name: near
          in: query
          description: where are the movie theatres located?
          required: true
          type: string
          format: location
          items:
            type: string
        - name: date
          in: query
          description: how many days from now are the desired showtimes? If not specified, 0 is assumed.
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: List of theatres
          schema:
            type: array
            items:
              $ref: '#/definitions/Theatre'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Movie:
    required:
      - name
      - showtimes
      - warning_thrown
    properties:
      name:
        type: string
        description: test
      mid:
        type: string
      misc_info:
        type: string
      rating:
        type: string
        default: ""
      runtime:
        type: integer
        default: 0
      showtimes:
        type: array
        items:
          type: string
        default: []
      url:
        type: string
        default: ""
      warning_thrown:
        type: boolean
  Theatre:
    required:
      - name
      - warning_thrown
    properties:
      address:
        type: string
      name:
        type: string
      phone_number:
        type: string
      program:
        type: array
        items:
          $ref: '#/definitions/Movie'
      tid:
        type: string
        default: null
      url:
        type: string
        default: ""
      warning_thrown:
        type: boolean
  
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string