swagger: "2.0"
info:
  version: 1.0.0
  title: google-movies-scraper
  description: A simple API to scrape [google.com/movies](http://google.com/movies).
    The API currently only accepts the `near` and `date` parameters that one would see
    from usage of google.com/movies.
    <br/><br/>
    The intended use of this service is to copy all
    of the URL proceeding `/movies` and paste it behind 
    [google-movies-scraper.herokuapp.com/movies](http://google-movies-scraper.herokuapp.com/movies),
    and then lo-and-behold! A JSON reformatting of all the movies you could see from the
    google.com/movies call. E.g.
    
      > http://google-movies-scraper.herokuapp.com/movies?near=Hinsdale%20Montana&date=2
    
    
    yields an array of JSON objects representing everything you'd see at
    
      
      > http://google.com/movies?near=Hinsdale%20Montana&date=2
    
    
    The way apiary.io processes SWAGGER definitions may make the response examples
    seem a bit confusing. Please see the JSON schema for parameter descriptions.
  contact:
    email: steven@gnobel.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: google-movies-scraper.herokuapp.com
basePath: /
schemes:
  - http
produces:
  - application/json
definitions:
  Showtime:
    type: string
    description: colon-separated, military time, 24H (e.g. HH:MM)
    example: '17:20'
  Movie:
    required:
      - name
      - showtimes
      - warning_thrown
    properties:
      name:
        type: string
        example: Kungfu Panda 3
      mid:
        type: string
        description: google.com/movie's 'movie id' for a particular movie.
        example: f119bc480
      misc_info:
        type: string
        description: Anything that follows a second '-' in the sub-header of a movie.
          This is typically the movie genre, for North American releases.
        example: Comedy/Romance - Trailer - IMDb
      rating:
        type: string
        default: ""
        example: "Rated R"
      runtime:
        type: integer
        default: 0
        description: This is parsed value that sometimes isn't available.
          If it cannot be parsed, the value of 0 is returned.
        example: 110
      showtimes:
        type: array
        items:
          $ref: '#/definitions/Showtime'
        default: []
        example: ['12:45', '13:30']
      url:
        type: string
        default: ""
        description: The url associated to a particular movie (and potentially theatre)
          returned from a particular crawl.
        example: '/movies?near=Hinsdale+MT&date=4&mid=e65f11b56eee1b30'
      warning_thrown:
        type: boolean
        description: returns false if any of the parsed values triggered warnings.
          You should double check the properties of an object with a value of false.
  Theatre:
    required:
      - name
      - warning_thrown
      - program
    properties:
      address:
        type: string
        example: 20 rue du Temple, Paris, France
        description: the parsed address (assumed to be in sub-header, below theatre name).
          This value can be empty.
        default: ''
      name:
        type: string
        example: Cineplex Odeon Latin Quarter Cinemas
      phone_number:
        type: string
        description: extracted from sub-header, below theatre name. This value can be empty.
        default: ''
        example: (514) 849-2244
      program:
        type: array
        items:
          $ref: '#/definitions/Movie'
      tid:
        type: string
        x-isnullable: true
        example: 43b016ae8041178e
        description: extracted from <a> surrounding theatre name. If only one theatre is
          returned from a query, this value will be null (since google won't wrap the theatre
          in an <a>)
      url:
        type: string
        default: ''
        description: extracted from <a> surrounding theatre name. If only one theatre is
          returned from a query, this value will be empty (since google won't wrap the theatre
          in an <a>).
      warning_thrown:
        type: boolean
        description: will return a false if any part of the theatre info extraction process
          triggered a warning. In said case, you should double check the object's properties.
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
paths:
  /movies:
    get:
      description: Return all theatres (and their showtimes) displayed in a call to google.com/movies.
      parameters:
        - name: near
          in: query
          description: where are the movie theatres located?
          required: true
          type: string
        - name: date
          in: query
          description: how many days from now are the desired showtimes? If not specified, 0 is assumed.
          required: false
          type: integer
          format: int32
          default: 0
      responses:

        400:
          description: Missing Parameter -- You've failed to specify `near` in the query string.
          schema:
            type: object
          examples: {
              "error": "need to specify 'near' parameter"
            }
        
        500:
          description: Internal Error -- Something went wrong during the scrape.
            This is probably a consequence of the CSS selection rules. Either one of
            the pages google has formatted breaks pattern, or google has changed
            a general pattern.
        
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Theatre'
        
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'